name: traefik
title: Traefik collector
overview:
  application:
    description: |
      [Traefik](https://traefik.io/traefik/) is a leading modern reverse proxy and load balancer that makes deploying
      microservices easy.
  collector:
    description: |
      This module will monitor one or more Traefik instances, depending on your configuration.
setup:
  prerequisites:
    list:
      - title: Enable built-in Prometheus exporter
        text: |
          To enable see [Prometheus exporter](https://doc.traefik.io/traefik/observability/metrics/p1rometheus/) documentation.
  configuration:
    options:
      description: |
        The following options can be defined globally: update_every, autodetection_retry.
      folding:
        title: All options
        enabled: true
      list:
        - name: update_every
          description: Data collection frequency.
          default: 1
          required: false
        - name: autodetection_retry
          description: Re-check interval in seconds. Zero means not to schedule re-check.
          default: 0
          required: false
        - name: url
          description: Server URL.
          default: http://127.0.0.1:8082/metrics
          required: true
        - name: timeout
          description: HTTP request timeout.
          default: 1
          required: false
        - name: username
          description: Username for basic HTTP authentication.
          default: '-'
          required: false
        - name: password
          description: Password for basic HTTP authentication.
          default: '-'
          required: false
        - name: proxy_url
          description: The Proxie's URL.
          default: '-'
          required: false
        - name: proxy_username
          description: Username for proxy basic HTTP authentication.
          default: '-'
          required: false
        - name: proxy_password
          description: Password for proxy basic HTTP authentication.
          default: '-'
          required: false
        - name: method
          description: HTTP request method.
          default: GET
          required: false
        - name: body
          description: HTTP request body.
          default: '-'
          required: false
        - name: headers
          description: HTTP request headers.
          default: '-'
          required: false
        - name: not_follow_redirects
          description: Whether to not follow redirects from the server.
          default: false
          required: false
        - name: tls_skip_verify
          description: Whether to skip verifying server's certificate chain and hostname.
          default: false
          required: false
        - name: tls_ca
          description: Certificate authority that client use when verifying server certificates.
          default: '-'
          required: false
        - name: tls_cert
          description: Client tls certificate.
          default: '-'
          required: false
        - name: tls_key
          description: Client tls key.
          default: '-'
          required: false
    examples:
      list:
        - name: Basic
          description: An example configuration.
          folding:
            title: Example
            enabled: true
          data: |
            jobs:
              - name: local
                url: http://127.0.0.1:8082/metrics
        - name: Basic HTTP auth
          description: Local server with basic HTTP authentication.
          folding:
            title: Example
            enabled: true
          data: |
            jobs:
              - name: local
                url: http://127.0.0.1:8082/metrics
                username: foo
                password: bar
        - name: Multi-instance
          description: |
            > **Note**: When you define multiple jobs, their names must be unique.
            
            Local and remote instances.
          folding:
            title: Example
            enabled: true
          data: |
            jobs:
              - name: local
                http://127.0.0.1:8082/metrics
            
              - name: remote
                http://192.0.2.0:8082/metrics
troubleshooting:
  problems:
    list: []
metrics:
  folding:
    title: Metrics
    enabled: false
  description: TBD
  scopes:
    - name: entrypoint, protocol
      description: TBD
      labels: []
      metrics:
        - name: traefik.entrypoint_requests
          description: Processed HTTP requests
          unit: requests/s
          chart_type: stacked
          dimensions:
            - name: 1xx
            - name: 2xx
            - name: 3xx
            - name: 4xx
            - name: 5xx
        - name: traefik.entrypoint_request_duration_average
          description: Average HTTP request processing time
          unit: milliseconds
          chart_type: stacked
          dimensions:
            - name: 1xx
            - name: 2xx
            - name: 3xx
            - name: 4xx
            - name: 5xx
        - name: traefik.entrypoint_open_connections
          description: Open connections
          unit: connections
          chart_type: stacked
          dimensions:
            - name: a dimension per HTTP method
