package mysql

import "github.com/netdata/go.d.plugin/modules"

type (
	// Charts is an alias for modules.Charts
	Charts = modules.Charts
	// Dims is an alias for modules.Dims
	Dims = modules.Dims
)

var charts = Charts{}

/* TODO (slave stats missing from my machine because I am not using any type of replication,
but should be:
	"seconds_behind_master": $seconds
	"slave_sql_running":     1 // if Yes
	"slave_io_running":      -1 // if !Yes
)
[slow_queries] = [4]
[select_full_range_join] = [0]
[bytes_sent] = [292534]
[handler_write] = [10163]
[innodb_buffer_pool_pages_dirty] = [0]
[innodb_data_pending_reads] = [0]
[innodb_os_log_pending_fsyncs] = [0]
[innodb_os_log_written] = [89600]
[key_reads] = [0]
[table_locks_immediate] = [23]
[binlog_cache_disk_use] = [0]
[connection_errors_internal] = [0]
[connection_errors_max_connections] = [0]
[connection_errors_tcpwrap] = [0]
[questions] = [63]
[innodb_buffer_pool_read_requests] = [21544]
[innodb_log_write_requests] = [765]
[innodb_log_writes] = [98]
[sort_scan] = [4]
[binlog_cache_use] = [0]
[com_delete] = [0]
[handler_savepoint] = [0]
[handler_update] = [346]
[innodb_buffer_pool_pages_misc] = [6]
[key_writes] = [0]
[connection_errors_accept] = [0]
[created_tmp_disk_tables] = [0]
[handler_prepare] = [0]
[handler_read_key] = [2374]
[handler_read_rnd] = [360]
[innodb_buffer_pool_read_ahead_evicted] = [0]
[innodb_data_writes] = [362]
[key_read_requests] = [0]
[com_insert] = [0]
[handler_read_rnd_next] = [20070]
[innodb_buffer_pool_pages_total] = [512]
[innodb_buffer_pool_read_ahead] = [14]
[innodb_data_written] = [5153792]
[innodb_rows_deleted] = [0]
[key_blocks_unused] = [6698]
[threads_created] = [3]
[aborted_connects] = [1]
[binlog_stmt_cache_disk_use] = [0]
[innodb_buffer_pool_pages_flushed] = [215]
[innodb_data_pending_fsyncs] = [0]
[innodb_data_read] = [15864832]
[select_range] = [0]
[select_range_check] = [0]
[threads_cached] = [0]
[created_tmp_tables] = [31]
[handler_read_first] = [39]
[innodb_buffer_pool_pages_data] = [257]
[innodb_buffer_pool_read_ahead_rnd] = [0]
[innodb_row_lock_current_waits] = [0]
[queries] = [105]
[sort_range] = [0]
[bytes_received] = [5648]
[connection_errors_peer_address] = [0]
[innodb_buffer_pool_write_requests] = [1945]
[key_blocks_not_flushed] = [0]
[table_locks_waited] = [0]
[created_tmp_files] = [5]
[innodb_data_reads] = [987]
[max_used_connections] = [3]
[open_files] = [7]
[threads_connected] = [3]
[threads_running] = [2]
[com_select] = [27]
[handler_read_next] = [6085]
[innodb_buffer_pool_bytes_data] = [4210688]
[select_full_join] = [2]
[opened_files] = [28]
[com_update] = [0]
[connection_errors_select] = [0]
[handler_commit] = [681]
[innodb_data_fsyncs] = [105]
[innodb_log_waits] = [0]
[innodb_rows_read] = [7214]
[innodb_rows_updated] = [346]
[binlog_stmt_cache_use] = [0]
[innodb_buffer_pool_wait_free] = [0]
[key_blocks_used] = [0]
[key_write_requests] = [0]
[max_connections] = [151]
[innodb_os_log_pending_writes] = [0]
[connections] = [31]
[handler_delete] = [0]
[handler_read_prev] = [0]
[handler_rollback] = [0]
[innodb_buffer_pool_bytes_dirty] = [0]
[innodb_buffer_pool_reads] = [950]
[innodb_os_log_fsyncs] = [71]
[select_scan] = [57]
[com_replace] = [0]
[handler_savepoint_rollback] = [0]
[innodb_buffer_pool_pages_free] = [249]
[innodb_rows_inserted] = [0]
[sort_merge_passes] = [0]
[innodb_data_pending_writes] = [0]


*/
