#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2018 Pawel Krupa (@paulfantom) - All Rights Reserved
# Permission to copy and modify is granted under the MIT license
#
# Requirements:
#   - hub command
#   - GITHUB_TOKEN variable set with GitHub token. Access level: repo.public_repo


set -e

if [ ! -f .gitignore ]; then
	echo "Run as ./travis/$(basename "$0") from top level directory of git repository"
	exit 1
fi

if [ -z ${TRAVIS_TAG+x} ]; then
    exit 1
fi

PR_TITLE="Use go.d.plugin in version ${TRAVIS_TAG}"
PR_MSG="This is an autogenerated pull request and it should consist of 17 line changes. Please review before merging."

export GIT_MAIL="bot@netdata.cloud"
export GIT_USER="netdatabot"
echo "--- Initialize git configuration ---"
git config user.email "${GIT_MAIL}"
git config user.name "${GIT_USER}"


CHECKSUM_FILE="$(pwd)/bin/sha256sums.txt"

git clone https://github.com/netdata/netdata.git netdata
cd netdata

cp "$CHECKSUM_FILE" packaging/go.d.checksums
sed -i "s/GO_PACKAGE_VERSION=\".*\"/GO_PACKAGE_VERSION=\"${TRAVIS_TAG}\"/g" netdata-installer.sh

git checkout -b new_go_d_version
git add netdata-installer.sh packaging/go.d.checksums
git commit -m "installer: include go.d.plugin version ${TRAVIS_TAG}"
hub pull-request -p -r paulkatsoulakis,ilyam8 -m "${PR_TITLE}" -m "${PR_MSG}"
